### ISSUE TITLE
Estória de usuário: verificar rendimento #1  TESTE MODELO

### ISSUE THREAD

**Issue by MateusgSales** [MateusgSales/Service-Car-Wash#1]
Identificador: E001   TESTE MODELO
Complexidade: média
Prioridade: alta
Descrição: Como um aluno cadastrado eu preciso saber qual foi meu percentual de acerto de questões nas avaliações que realizei para verificar se o meu rendimento na disciplina está satisfatório.

**Comment by ericknilsen** [comment]
Remova essa estória, pois não faz parte do seu sistema.
