### ISSUE TITLE
Estória de usuário: Lavagem de carro Delivery_Agendamento de Serviço.

### ISSUE THREAD

**Issue by MateusgSales** [MateusgSales/Service-Car-Wash#5]
Identificador: E004
Complexidade: Média
Prioridade: alta
Descrição: Como prestador de serviço preciso que na interface exista um forma de agendamento de serviço.

**Comment by ericknilsen** [comment]
Não se refira a "interface" ou qualquer elemento do sistema. Qual o objetivo/funcionalidade dessa estória?
